version: 0.2

env:
  variables:
    BACKEND_DIR: "backend"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd $BACKEND_DIR
      - npm install
  build:
    commands:
      - echo "Build backend (if needed)..."
  post_build:
    commands:
      - echo "Packaging backend for CodeDeploy..."
      - cd ..
      - mkdir -p codedeploy
      - cp -r $BACKEND_DIR/* codedeploy/
      - cp appspec.yml codedeploy/
artifacts:
  files:
    - codedeploy/**/*
